<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $country_list = [
            ['code'=>"AF", "name" => "Afghanistan", "phone" => 93, "continent" => "Asia"],
            ['code'=>"AX", "name" => "Aland Islands", "phone" => 358, "continent" => "Europe"],
            ['code'=>"AL", "name" => "Albania", "phone" => 355, "continent" => "Europe"],
            ['code'=>"DZ", "name" => "Algeria", "phone" => 213, "continent" => "Africa"],
            ['code'=>"AS", "name" => "American Samoa", "phone" => 1684, "continent" => "Oceania"],
            ['code'=>"AD", "name" => "Andorra", "phone" => 376, "continent" => "Europe"],
            ['code'=>"AO", "name" => "Angola", "phone" => 244, "continent" => "Africa"],
            ['code'=>"AI", "name" => "Anguilla", "phone" => 1264, "continent" => "North America"],
            ['code'=>"AQ", "name" => "Antarctica", "phone" => 672, "continent" => "Antarctica"],
            ['code'=>"AG", "name" => "Antigua and Barbuda", "phone" => 1268, "continent" => "North America"],
            ['code'=>"AR", "name" => "Argentina", "phone" => 54, "continent" => "South America"],
            ['code'=>"AM", "name" => "Armenia", "phone" => 374, "continent" => "Asia"],
            ['code'=>"AW", "name" => "Aruba", "phone" => 297, "continent" => "North America"],
            ['code'=>"AU", "name" => "Australia", "phone" => 61, "continent" => "Oceania"],
            ['code'=>"AT", "name" => "Austria", "phone" => 43, "continent" => "Europe"],
            ['code'=>"AZ", "name" => "Azerbaijan", "phone" => 994, "continent" => "Asia"],
            ['code'=>"BS", "name" => "Bahamas", "phone" => 1242, "continent" => "North America"],
            ['code'=>"BH", "name" => "Bahrain", "phone" => 973, "continent" => "Asia"],
            ['code'=>"BD", "name" => "Bangladesh", "phone" => 880, "continent" => "Asia"],
            ['code'=>"BB", "name" => "Barbados", "phone" => 1246, "continent" => "North America"],
            ['code'=>"BY", "name" => "Belarus", "phone" => 375, "continent" => "Europe"],
            ['code'=>"BE", "name" => "Belgium", "phone" => 32, "continent" => "Europe"],
            ['code'=>"BZ", "name" => "Belize", "phone" => 501, "continent" => "North America"],
            ['code'=>"BJ", "name" => "Benin", "phone" => 229, "continent" => "Africa"],
            ['code'=>"BM", "name" => "Bermuda", "phone" => 1441, "continent" => "North America"],
            ['code'=>"BT", "name" => "Bhutan", "phone" => 975, "continent" => "Asia"],
            ['code'=>"BO", "name" => "Bolivia", "phone" => 591, "continent" => "South America"],
            ['code'=>"BQ", "name" => "Bonaire, Sint Eustatius and Saba", "phone" => 599, "continent" => "North America"],
            ['code'=>"BA", "name" => "Bosnia and Herzegovina", "phone" => 387, "continent" => "Europe"],
            ['code'=>"BW", "name" => "Botswana", "phone" => 267, "continent" => "Africa"],
            ['code'=>"BV", "name" => "Bouvet Island", "phone" => 55, "continent" => "Antarctica"],
            ['code'=>"BR", "name" => "Brazil", "phone" => 55, "continent" => "South America"],
            ['code'=>"IO", "name" => "British Indian Ocean Territory", "phone" => 246, "continent" => "Asia"],
            ['code'=>"BN", "name" => "Brunei Darussalam", "phone" => 673, "continent" => "Asia"],
            ['code'=>"BG", "name" => "Bulgaria", "phone" => 359, "continent" => "Europe"],
            ['code'=>"BF", "name" => "Burkina Faso", "phone" => 226, "continent" => "Africa"],
            ['code'=>"BI", "name" => "Burundi", "phone" => 257, "continent" => "Africa"],
            ['code'=>"KH", "name" => "Cambodia", "phone" => 855, "continent" => "Asia"],
            ['code'=>"CM", "name" => "Cameroon", "phone" => 237, "continent" => "Africa"],
            ['code'=>"CA", "name" => "Canada", "phone" => 1, "continent" => "North America"],
            ['code'=>"CV", "name" => "Cape Verde", "phone" => 238, "continent" => "Africa"],
            ['code'=>"KY", "name" => "Cayman Islands", "phone" => 1345, "continent" => "North America"],
            ['code'=>"CF", "name" => "Central African Republic", "phone" => 236, "continent" => "Africa"],
            ['code'=>"TD", "name" => "Chad", "phone" => 235, "continent" => "Africa"],
            ['code'=>"CL", "name" => "Chile", "phone" => 56, "continent" => "South America"],
            ['code'=>"CN", "name" => "China", "phone" => 86, "continent" => "Asia"],
            ['code'=>"CX", "name" => "Christmas Island", "phone" => 61, "continent" => "Asia"],
            ['code'=>"CC", "name" => "Cocos (Keeling) Islands", "phone" => 672, "continent" => "Asia"],
            ['code'=>"CO", "name" => "Colombia", "phone" => 57, "continent" => "South America"],
            ['code'=>"KM", "name" => "Comoros", "phone" => 269, "continent" => "Africa"],
            ['code'=>"CG", "name" => "Congo", "phone" => 242, "continent" => "Africa"],
            ['code'=>"CD", "name" => "Congo, Democratic Republic of the Congo", "phone" => 242, "continent" => "Africa"],
            ['code'=>"CK", "name" => "Cook Islands", "phone" => 682, "continent" => "Oceania"],
            ['code'=>"CR", "name" => "Costa Rica", "phone" => 506, "continent" => "North America"],
            ['code'=>"CI", "name" => "Cote D'Ivoire", "phone" => 225, "continent" => "Africa"],
            ['code'=>"HR", "name" => "Croatia", "phone" => 385, "continent" => "Europe"],
            ['code'=>"CU", "name" => "Cuba", "phone" => 53, "continent" => "North America"],
            ['code'=>"CW", "name" => "Curacao", "phone" => 599, "continent" => "North America"],
            ['code'=>"CY", "name" => "Cyprus", "phone" => 357, "continent" => "Asia"],
            ['code'=>"CZ", "name" => "Czech Republic", "phone" => 420, "continent" => "Europe"],
            ['code'=>"DK", "name" => "Denmark", "phone" => 45, "continent" => "Europe"],
            ['code'=>"DJ", "name" => "Djibouti", "phone" => 253, "continent" => "Africa"],
            ['code'=>"DM", "name" => "Dominica", "phone" => 1767, "continent" => "North America"],
            ['code'=>"DO", "name" => "Dominican Republic", "phone" => 1809, "continent" => "North America"],
            ['code'=>"EC", "name" => "Ecuador", "phone" => 593, "continent" => "South America"],
            ['code'=>"EG", "name" => "Egypt", "phone" => 20, "continent" => "Africa"],
            ['code'=>"SV", "name" => "El Salvador", "phone" => 503, "continent" => "North America"],
            ['code'=>"GQ", "name" => "Equatorial Guinea", "phone" => 240, "continent" => "Africa"],
            ['code'=>"ER", "name" => "Eritrea", "phone" => 291, "continent" => "Africa"],
            ['code'=>"EE", "name" => "Estonia", "phone" => 372, "continent" => "Europe"],
            ['code'=>"ET", "name" => "Ethiopia", "phone" => 251, "continent" => "Africa"],
            ['code'=>"FK", "name" => "Falkland Islands (Malvinas)", "phone" => 500, "continent" => "South America"],
            ['code'=>"FO", "name" => "Faroe Islands", "phone" => 298, "continent" => "Europe"],
            ['code'=>"FJ", "name" => "Fiji", "phone" => 679, "continent" => "Oceania"],
            ['code'=>"FI", "name" => "Finland", "phone" => 358, "continent" => "Europe"],
            ['code'=>"FR", "name" => "France", "phone" => 33, "continent" => "Europe"],
            ['code'=>"GF", "name" => "French Guiana", "phone" => 594, "continent" => "South America"],
            ['code'=>"PF", "name" => "French Polynesia", "phone" => 689, "continent" => "Oceania"],
            ['code'=>"TF", "name" => "French Southern Territories", "phone" => 262, "continent" => "Antarctica"],
            ['code'=>"GA", "name" => "Gabon", "phone" => 241, "continent" => "Africa"],
            ['code'=>"GM", "name" => "Gambia", "phone" => 220, "continent" => "Africa"],
            ['code'=>"GE", "name" => "Georgia", "phone" => 995, "continent" => "Asia"],
            ['code'=>"DE", "name" => "Germany", "phone" => 49, "continent" => "Europe"],
            ['code'=>"GH", "name" => "Ghana", "phone" => 233, "continent" => "Africa"],
            ['code'=>"GI", "name" => "Gibraltar", "phone" => 350, "continent" => "Europe"],
            ['code'=>"GR", "name" => "Greece", "phone" => 30, "continent" => "Europe"],
            ['code'=>"GL", "name" => "Greenland", "phone" => 299, "continent" => "North America"],
            ['code'=>"GD", "name" => "Grenada", "phone" => 1473, "continent" => "North America"],
            ['code'=>"GP", "name" => "Guadeloupe", "phone" => 590, "continent" => "North America"],
            ['code'=>"GU", "name" => "Guam", "phone" => 1671, "continent" => "Oceania"],
            ['code'=>"GT", "name" => "Guatemala", "phone" => 502, "continent" => "North America"],
            ['code'=>"GG", "name" => "Guernsey", "phone" => 44, "continent" => "Europe"],
            ['code'=>"GN", "name" => "Guinea", "phone" => 224, "continent" => "Africa"],
            ['code'=>"GW", "name" => "Guinea-Bissau", "phone" => 245, "continent" => "Africa"],
            ['code'=>"GY", "name" => "Guyana", "phone" => 592, "continent" => "South America"],
            ['code'=>"HT", "name" => "Haiti", "phone" => 509, "continent" => "North America"],
            ['code'=>"HM", "name" => "Heard Island and McDonald Islands", "phone" => 0, "continent" => "Antarctica"],
            ['code'=>"VA", "name" => "Holy See (Vatican City State)", "phone" => 39, "continent" => "Europe"],
            ['code'=>"HN", "name" => "Honduras", "phone" => 504, "continent" => "North America"],
            ['code'=>"HK", "name" => "Hong Kong", "phone" => 852, "continent" => "Asia"],
            ['code'=>"HU", "name" => "Hungary", "phone" => 36, "continent" => "Europe"],
            ['code'=>"IS", "name" => "Iceland", "phone" => 354, "continent" => "Europe"],
            ['code'=>"IN", "name" => "India", "phone" => 91, "continent" => "Asia"],
            ['code'=>"ID", "name" => "Indonesia", "phone" => 62, "continent" => "Asia"],
            ['code'=>"IR", "name" => "Iran, Islamic Republic of", "phone" => 98, "continent" => "Asia"],
            ['code'=>"IQ", "name" => "Iraq", "phone" => 964, "continent" => "Asia"],
            ['code'=>"IE", "name" => "Ireland", "phone" => 353, "continent" => "Europe"],
            ['code'=>"IM", "name" => "Isle of Man", "phone" => 44, "continent" => "Europe"],
            ['code'=>"IL", "name" => "Israel", "phone" => 972, "continent" => "Asia"],
            ['code'=>"IT", "name" => "Italy", "phone" => 39, "continent" => "Europe"],
            ['code'=>"JM", "name" => "Jamaica", "phone" => 1876, "continent" => "North America"],
            ['code'=>"JP", "name" => "Japan", "phone" => 81, "continent" => "Asia"],
            ['code'=>"JE", "name" => "Jersey", "phone" => 44, "continent" => "Europe"],
            ['code'=>"JO", "name" => "Jordan", "phone" => 962, "continent" => "Asia"],
            ['code'=>"KZ", "name" => "Kazakhstan", "phone" => 7, "continent" => "Asia"],
            ['code'=>"KE", "name" => "Kenya", "phone" => 254, "continent" => "Africa"],
            ['code'=>"KI", "name" => "Kiribati", "phone" => 686, "continent" => "Oceania"],
            ['code'=>"KP", "name" => "Korea, Democratic People's Republic of", "phone" => 850, "continent" => "Asia"],
            ['code'=>"KR", "name" => "Korea, Republic of", "phone" => 82, "continent" => "Asia"],
            ['code'=>"XK", "name" => "Kosovo", "phone" => 383, "continent" => "Europe"],
            ['code'=>"KW", "name" => "Kuwait", "phone" => 965, "continent" => "Asia"],
            ['code'=>"KG", "name" => "Kyrgyzstan", "phone" => 996, "continent" => "Asia"],
            ['code'=>"LA", "name" => "Lao People's Democratic Republic", "phone" => 856, "continent" => "Asia"],
            ['code'=>"LV", "name" => "Latvia", "phone" => 371, "continent" => "Europe"],
            ['code'=>"LB", "name" => "Lebanon", "phone" => 961, "continent" => "Asia"],
            ['code'=>"LS", "name" => "Lesotho", "phone" => 266, "continent" => "Africa"],
            ['code'=>"LR", "name" => "Liberia", "phone" => 231, "continent" => "Africa"],
            ['code'=>"LY", "name" => "Libyan Arab Jamahiriya", "phone" => 218, "continent" => "Africa"],
            ['code'=>"LI", "name" => "Liechtenstein", "phone" => 423, "continent" => "Europe"],
            ['code'=>"LT", "name" => "Lithuania", "phone" => 370, "continent" => "Europe"],
            ['code'=>"LU", "name" => "Luxembourg", "phone" => 352, "continent" => "Europe"],
            ['code'=>"MO", "name" => "Macao", "phone" => 853, "continent" => "Asia"],
            ['code'=>"MK", "name" => "Macedonia, the Former Yugoslav Republic of", "phone" => 389, "continent" => "Europe"],
            ['code'=>"MG", "name" => "Madagascar", "phone" => 261, "continent" => "Africa"],
            ['code'=>"MW", "name" => "Malawi", "phone" => 265, "continent" => "Africa"],
            ['code'=>"MY", "name" => "Malaysia", "phone" => 60, "continent" => "Asia"],
            ['code'=>"MV", "name" => "Maldives", "phone" => 960, "continent" => "Asia"],
            ['code'=>"ML", "name" => "Mali", "phone" => 223, "continent" => "Africa"],
            ['code'=>"MT", "name" => "Malta", "phone" => 356, "continent" => "Europe"],
            ['code'=>"MH", "name" => "Marshall Islands", "phone" => 692, "continent" => "Oceania"],
            ['code'=>"MQ", "name" => "Martinique", "phone" => 596, "continent" => "North America"],
            ['code'=>"MR", "name" => "Mauritania", "phone" => 222, "continent" => "Africa"],
            ['code'=>"MU", "name" => "Mauritius", "phone" => 230, "continent" => "Africa"],
            ['code'=>"YT", "name" => "Mayotte", "phone" => 262, "continent" => "Africa"],
            ['code'=>"MX", "name" => "Mexico", "phone" => 52, "continent" => "North America"],
            ['code'=>"FM", "name" => "Micronesia, Federated States of", "phone" => 691, "continent" => "Oceania"],
            ['code'=>"MD", "name" => "Moldova, Republic of", "phone" => 373, "continent" => "Europe"],
            ['code'=>"MC", "name" => "Monaco", "phone" => 377, "continent" => "Europe"],
            ['code'=>"MN", "name" => "Mongolia", "phone" => 976, "continent" => "Asia"],
            ['code'=>"ME", "name" => "Montenegro", "phone" => 382, "continent" => "Europe"],
            ['code'=>"MS", "name" => "Montserrat", "phone" => 1664, "continent" => "North America"],
            ['code'=>"MA", "name" => "Morocco", "phone" => 212, "continent" => "Africa"],
            ['code'=>"MZ", "name" => "Mozambique", "phone" => 258, "continent" => "Africa"],
            ['code'=>"MM", "name" => "Myanmar", "phone" => 95, "continent" => "Asia"],
            ['code'=>"NA", "name" => "Namibia", "phone" => 264, "continent" => "Africa"],
            ['code'=>"NR", "name" => "Nauru", "phone" => 674, "continent" => "Oceania"],
            ['code'=>"NP", "name" => "Nepal", "phone" => 977, "continent" => "Asia"],
            ['code'=>"NL", "name" => "Netherlands", "phone" => 31, "continent" => "Europe"],
            ['code'=>"AN", "name" => "Netherlands Antilles", "phone" => 599, "continent" => "North America"],
            ['code'=>"NC", "name" => "New Caledonia", "phone" => 687, "continent" => "Oceania"],
            ['code'=>"NZ", "name" => "New Zealand", "phone" => 64, "continent" => "Oceania"],
            ['code'=>"NI", "name" => "Nicaragua", "phone" => 505, "continent" => "North America"],
            ['code'=>"NE", "name" => "Niger", "phone" => 227, "continent" => "Africa"],
            ['code'=>"NG", "name" => "Nigeria", "phone" => 234, "continent" => "Africa"],
            ['code'=>"NU", "name" => "Niue", "phone" => 683, "continent" => "Oceania"],
            ['code'=>"NF", "name" => "Norfolk Island", "phone" => 672, "continent" => "Oceania"],
            ['code'=>"MP", "name" => "Northern Mariana Islands", "phone" => 1670, "continent" => "Oceania"],
            ['code'=>"NO", "name" => "Norway", "phone" => 47, "continent" => "Europe"],
            ['code'=>"OM", "name" => "Oman", "phone" => 968, "continent" => "Asia"],
            ['code'=>"PK", "name" => "Pakistan", "phone" => 92, "continent" => "Asia"],
            ['code'=>"PW", "name" => "Palau", "phone" => 680, "continent" => "Oceania"],
            ['code'=>"PS", "name" => "Palestinian Territory, Occupied", "phone" => 970, "continent" => "Asia"],
            ['code'=>"PA", "name" => "Panama", "phone" => 507, "continent" => "North America"],
            ['code'=>"PG", "name" => "Papua New Guinea", "phone" => 675, "continent" => "Oceania"],
            ['code'=>"PY", "name" => "Paraguay", "phone" => 595, "continent" => "South America"],
            ['code'=>"PE", "name" => "Peru", "phone" => 51, "continent" => "South America"],
            ['code'=>"PH", "name" => "Philippines", "phone" => 63, "continent" => "Asia"],
            ['code'=>"PN", "name" => "Pitcairn", "phone" => 64, "continent" => "Oceania"],
            ['code'=>"PL", "name" => "Poland", "phone" => 48, "continent" => "Europe"],
            ['code'=>"PT", "name" => "Portugal", "phone" => 351, "continent" => "Europe"],
            ['code'=>"PR", "name" => "Puerto Rico", "phone" => 1787, "continent" => "North America"],
            ['code'=>"QA", "name" => "Qatar", "phone" => 974, "continent" => "Asia"],
            ['code'=>"RE", "name" => "Reunion", "phone" => 262, "continent" => "Africa"],
            ['code'=>"RO", "name" => "Romania", "phone" => 40, "continent" => "Europe"],
            ['code'=>"RU", "name" => "Russian Federation", "phone" => 7, "continent" => "Asia"],
            ['code'=>"RW", "name" => "Rwanda", "phone" => 250, "continent" => "Africa"],
            ['code'=>"BL", "name" => "Saint Barthelemy", "phone" => 590, "continent" => "North America"],
            ['code'=>"SH", "name" => "Saint Helena", "phone" => 290, "continent" => "Africa"],
            ['code'=>"KN", "name" => "Saint Kitts and Nevis", "phone" => 1869, "continent" => "North America"],
            ['code'=>"LC", "name" => "Saint Lucia", "phone" => 1758, "continent" => "North America"],
            ['code'=>"MF", "name" => "Saint Martin", "phone" => 590, "continent" => "North America"],
            ['code'=>"PM", "name" => "Saint Pierre and Miquelon", "phone" => 508, "continent" => "North America"],
            ['code'=>"VC", "name" => "Saint Vincent and the Grenadines", "phone" => 1784, "continent" => "North America"],
            ['code'=>"WS", "name" => "Samoa", "phone" => 684, "continent" => "Oceania"],
            ['code'=>"SM", "name" => "San Marino", "phone" => 378, "continent" => "Europe"],
            ['code'=>"ST", "name" => "Sao Tome and Principe", "phone" => 239, "continent" => "Africa"],
            ['code'=>"SA", "name" => "Saudi Arabia", "phone" => 966, "continent" => "Asia"],
            ['code'=>"SN", "name" => "Senegal", "phone" => 221, "continent" => "Africa"],
            ['code'=>"RS", "name" => "Serbia", "phone" => 381, "continent" => "Europe"],
            ['code'=>"CS", "name" => "Serbia and Montenegro", "phone" => 381, "continent" => "Europe"],
            ['code'=>"SC", "name" => "Seychelles", "phone" => 248, "continent" => "Africa"],
            ['code'=>"SL", "name" => "Sierra Leone", "phone" => 232, "continent" => "Africa"],
            ['code'=>"SG", "name" => "Singapore", "phone" => 65, "continent" => "Asia"],
            ['code'=>"SX", "name" => "St Martin", "phone" => 721, "continent" => "North America"],
            ['code'=>"SK", "name" => "Slovakia", "phone" => 421, "continent" => "Europe"],
            ['code'=>"SI", "name" => "Slovenia", "phone" => 386, "continent" => "Europe"],
            ['code'=>"SB", "name" => "Solomon Islands", "phone" => 677, "continent" => "Oceania"],
            ['code'=>"SO", "name" => "Somalia", "phone" => 252, "continent" => "Africa"],
            ['code'=>"ZA", "name" => "South Africa", "phone" => 27, "continent" => "Africa"],
            ['code'=>"GS", "name" => "South Georgia and the South Sandwich Islands", "phone" => 500, "continent" => "Antarctica"],
            ['code'=>"SS", "name" => "South Sudan", "phone" => 211, "continent" => "Africa"],
            ['code'=>"ES", "name" => "Spain", "phone" => 34, "continent" => "Europe"],
            ['code'=>"LK", "name" => "Sri Lanka", "phone" => 94, "continent" => "Asia"],
            ['code'=>"SD", "name" => "Sudan", "phone" => 249, "continent" => "Africa"],
            ['code'=>"SR", "name" => "Suriname", "phone" => 597, "continent" => "South America"],
            ['code'=>"SJ", "name" => "Svalbard and Jan Mayen", "phone" => 47, "continent" => "Europe"],
            ['code'=>"SZ", "name" => "Swaziland", "phone" => 268, "continent" => "Africa"],
            ['code'=>"SE", "name" => "Sweden", "phone" => 46, "continent" => "Europe"],
            ['code'=>"CH", "name" => "Switzerland", "phone" => 41, "continent" => "Europe"],
            ['code'=>"SY", "name" => "Syrian Arab Republic", "phone" => 963, "continent" => "Asia"],
            ['code'=>"TW", "name" => "Taiwan, Province of China", "phone" => 886, "continent" => "Asia"],
            ['code'=>"TJ", "name" => "Tajikistan", "phone" => 992, "continent" => "Asia"],
            ['code'=>"TZ", "name" => "Tanzania, United Republic of", "phone" => 255, "continent" => "Africa"],
            ['code'=>"TH", "name" => "Thailand", "phone" => 66, "continent" => "Asia"],
            ['code'=>"TL", "name" => "Timor-Leste", "phone" => 670, "continent" => "Asia"],
            ['code'=>"TG", "name" => "Togo", "phone" => 228, "continent" => "Africa"],
            ['code'=>"TK", "name" => "Tokelau", "phone" => 690, "continent" => "Oceania"],
            ['code'=>"TO", "name" => "Tonga", "phone" => 676, "continent" => "Oceania"],
            ['code'=>"TT", "name" => "Trinidad and Tobago", "phone" => 1868, "continent" => "North America"],
            ['code'=>"TN", "name" => "Tunisia", "phone" => 216, "continent" => "Africa"],
            ['code'=>"TR", "name" => "Turkey", "phone" => 90, "continent" => "Asia"],
            ['code'=>"TM", "name" => "Turkmenistan", "phone" => 7370, "continent" => "Asia"],
            ['code'=>"TC", "name" => "Turks and Caicos Islands", "phone" => 1649, "continent" => "North America"],
            ['code'=>"TV", "name" => "Tuvalu", "phone" => 688, "continent" => "Oceania"],
            ['code'=>"UG", "name" => "Uganda", "phone" => 256, "continent" => "Africa"],
            ['code'=>"UA", "name" => "Ukraine", "phone" => 380, "continent" => "Europe"],
            ['code'=>"AE", "name" => "United Arab Emirates", "phone" => 971, "continent" => "Asia"],
            ['code'=>"GB", "name" => "United Kingdom", "phone" => 44, "continent" => "Europe"],
            ['code'=>"US", "name" => "United States", "phone" => 1, "continent" => "North America"],
            ['code'=>"UM", "name" => "United States Minor Outlying Islands", "phone" => 1, "continent" => "North America"],
            ['code'=>"UY", "name" => "Uruguay", "phone" => 598, "continent" => "South America"],
            ['code'=>"UZ", "name" => "Uzbekistan", "phone" => 998, "continent" => "Asia"],
            ['code'=>"VU", "name" => "Vanuatu", "phone" => 678, "continent" => "Oceania"],
            ['code'=>"VE", "name" => "Venezuela", "phone" => 58, "continent" => "South America"],
            ['code'=>"VN", "name" => "Viet Nam", "phone" => 84, "continent" => "Asia"],
            ['code'=>"VG", "name" => "Virgin Islands, British", "phone" => 1284, "continent" => "North America"],
            ['code'=>"VI", "name" => "Virgin Islands, U.s.", "phone" => 1340, "continent" => "North America"],
            ['code'=>"WF", "name" => "Wallis and Futuna", "phone" => 681, "continent" => "Oceania"],
            ['code'=>"EH", "name" => "Western Sahara", "phone" => 212, "continent" => "Africa"],
            ['code'=>"YE", "name" => "Yemen", "phone" => 967, "continent" => "Asia"],
            ['code'=>"ZM", "name" => "Zambia", "phone" => 260, "continent" => "Africa"],
            ['code'=>"ZW", "name" => "Zimbabwe", "phone" => 263, "continent" => "Africa"]
        ];

        foreach ($country_list as $country) {
            Country::create([
                'name'=>$country['name'],
                'code'=>$country['code'],
                'phone'=>$country['phone'],
                'continent'=>$country['continent'],
            ]);
        }
    }
}
